package com.zhanggg.business.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("khzb", "id", Khzb.class);
		arp.addMapping("lj", "id", Lj.class);
		arp.addMapping("zlml", "id", Zlml.class);
		arp.addMapping("dict", "id", Dict.class);
	}
}

