package com.zhanggg.business.model;

import com.zhanggg.business.model.base.BaseLj;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lj extends BaseLj<Lj> {
	public static final Lj dao = new Lj().dao();
}
