package com.zhanggg.business.model;

import com.zhanggg.business.model.base.BaseZlml;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zlml extends BaseZlml<Zlml> {
	public static final Zlml dao = new Zlml().dao();
}
