package com.zhanggg.business.model;

import com.zhanggg.business.model.base.BaseKhzb;

/**
 * Generated by JFinal.
 * 考核指标
 */
@SuppressWarnings("serial")
public class Khzb extends BaseKhzb<Khzb> {
	public static final Khzb dao = new Khzb().dao();
}
