package com.zhanggg.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDict<M extends BaseDict<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setGroup(java.lang.String group) {
		set("group", group);
		return (M)this;
	}

	public java.lang.String getGroup() {
		return get("group");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setVal(java.lang.String val) {
		set("val", val);
		return (M)this;
	}

	public java.lang.String getVal() {
		return get("val");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

}
