package com.zhanggg.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseZlml<M extends BaseZlml<M>> extends Model<M> implements IBean {

	public M setID(Integer ID) {
		set("ID", ID);
		return (M)this;
	}

	public Integer getID() {
		return get("ID");
	}

	public M setZj(java.lang.String zj) {
		set("zj", zj);
		return (M)this;
	}

	public java.lang.String getZj() {
		return get("zj");
	}

	public M setNr(java.lang.String nr) {
		set("nr", nr);
		return (M)this;
	}

	public java.lang.String getNr() {
		return get("nr");
	}

	public M setFatherZJ(Integer fatherZJ) {
		set("fatherZJ", fatherZJ);
		return (M)this;
	}

	public Integer getFatherZJ() {
		return get("fatherZJ");
	}

	public M setPx(Integer px) {
		set("px", px);
		return (M)this;
	}

	public Integer getPx() {
		return get("px");
	}

}
